AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  ExcludedMethods: ['let', 'it', 'describe', 'context', 'specify']

Metrics/MethodLength:
  Max: 25
